name: Release-Container
on:
  push:
    branches: 
    - master
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:  
#        username: ${{ github.actor }}
        username: kubernoah
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tag_with_ref: true
        tag_with_sha: true
